In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,precision_recall_fscore_support
import warnings
import os

In [2]:
#load the dataset
a1=pd.read_excel("case_study1_internal_bank_dataset.xlsx")
a2=pd.read_excel("case_study2_civil_dataset.xlsx")

In [3]:
df1=a1.copy()
df2=a2.copy()

In [4]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32

In [5]:
df1.shape

(51336, 26)

In [6]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [7]:
df2.shape

(51336, 62)

In [8]:
#remove nulls 
df1=df1.loc[df1['Age_Oldest_TL']!=-99999]

In [9]:
df1['Age_Oldest_TL'].head()

0     72
1      7
2     47
3      5
4    131
Name: Age_Oldest_TL, dtype: int64

In [10]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32

In [11]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

# now we are going to remove -9999 value from df2 where there are so many -9999 in many columns
* so we iterate with loop and see if the -99999 values are 10000 then we remove that column from dataset , else remove the row only

In [12]:
#code for this 
columns_to_be_removed=[]
for i in df2.columns:
    if df2.loc[df2[i]==-99999].shape[0]>10000:
        columns_to_be_removed.append(i)

In [13]:
columns_to_be_removed

['time_since_first_deliquency',
 'time_since_recent_deliquency',
 'max_delinquency_level',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'CC_utilization',
 'PL_utilization',
 'max_unsec_exposure_inPct']

In [14]:
#now droping the columns
df2=df2.drop(columns_to_be_removed,axis=1)

In [15]:
df2.head()

,PROSPECTID,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,11,29,0,0,0,0,0,21,...,0.0,0.0,0.0,0.0,1,0,PL,PL,696,P2
1,2,47,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,9,25,1,9,8,0,0,10,...,0.0,0.0,0.0,0.0,1,0,ConsumerLoan,others,693,P2
3,4,-99999,0,0,0,0,0,0,0,5,...,0.0,0.0,0.0,0.0,0,0,others,others,673,P2
4,5,583,0,0,0,0,0,0,0,53,...,0.0,0.0,0.0,0.0,0,0,AL,AL,753,P1

In [16]:
# now we are simply remov the -99999  values from rest of the colum
for i in df2.columns:
    df2=df2.loc[df2[i]!=-99999]

In [17]:
df2.head()

,PROSPECTID,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,11,29,0,0,0,0,0,21,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,47,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,9,25,1,9,8,0,0,10,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
4,5,583,0,0,0,0,0,0,0,53,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
5,6,245,14,270,0,0,0,13,11,5,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3

In [18]:
df2.shape

(42066, 54)

# merging columns

In [19]:
#checking common columns names
for i in list(df1.columns):
    if i in list(df2.columns):
        print(i)

PROSPECTID

In [20]:
# now merging two datasets, inner join so that no nulls are present
df=pd.merge(df1,df2,how='inner',left_on=['PROSPECTID'],right_on=['PROSPECTID'])

In [21]:
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.0,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3

In [22]:
df.shape

(42064, 79)

In [23]:
df.isna().sum()

PROSPECTID             0
Total_TL               0
Tot_Closed_TL          0
Tot_Active_TL          0
Total_TL_opened_L6M    0
                      ..
GL_Flag                0
last_prod_enq2         0
first_prod_enq2        0
Credit_Score           0
Approved_Flag          0
Length: 79, dtype: int64

# seperating the columns ( numerical , categorical)

In [24]:
# now check how many categorical columns are present
for i in df.columns:
    if df[i].dtype=='object':
        print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [25]:
# now we are going to apply chi-square test
#here all the featuers have p value less than <=0.05, we will accept all
from scipy.stats import chi2_contingency
for i in ['MARITALSTATUS','EDUCATION','GENDER','last_prod_enq2','first_prod_enq2','Approved_Flag']:
    chi2,pval,_,_=chi2_contingency(pd.crosstab(df[i],df['Approved_Flag']))
    print(i,'---',pval)

MARITALSTATUS --- 3.578180861038862e-233
EDUCATION --- 2.6942265249737532e-30
GENDER --- 1.907936100186563e-05
last_prod_enq2 --- 0.0
first_prod_enq2 --- 7.84997610555419e-287
Approved_Flag --- 0.0

In [26]:
#VIF for numerical feature
numerical_columns=[]
for i in df.columns:
    if df[i].dtype !='object' and i not in ['PROSPECTED','Approved_Flag']:
        numerical_columns.append(i)

In [27]:
len(numerical_columns)

73

In [28]:
# VIF Sequentially check
vif_data=df[numerical_columns]
total_columns=vif_data.shape[1]
columns_to_be_kept=[]
column_index=0

for i in range(0,total_columns):
    vif_value=variance_inflation_factor(vif_data,column_index)
    print(column_index,'------',vif_value)
    
    if vif_value<=6:
        columns_to_be_kept.append(numerical_columns[i])
        column_index=column_index+1
    else:
        vif_data=vif_data.drop([numerical_columns[i]],axis=1)

0 ------ 1.0014714453751743

C:\Users\rajkr\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

1 ------ inf

C:\Users\rajkr\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

1 ------ inf
1 ------ 11.320645246142803
1 ------ 8.364064272336133
1 ------ 6.520792569522158
1 ------ 5.1498060557107745
2 ------ 2.6112073771674944

C:\Users\rajkr\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

3 ------ inf
3 ------ 1789.5578922792413
3 ------ 8.601096683974646
3 ------ 3.832851362174614
4 ------ 6.099768198336679
4 ------ 5.5814467511930905
5 ------ 1.9856551389669772

C:\Users\rajkr\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

6 ------ inf
6 ------ 4.809807520859604
7 ------ 23.27288184101288
7 ------ 30.596519319624697
7 ------ 4.384812209111584
8 ------ 3.064673562463159
9 ------ 2.8986527303140033
10 ------ 4.377945210179218
11 ------ 2.2078562659546592
12 ------ 4.9200182258988345
13 ------ 5.215354852494451
14 ------ 3.3862072703025055
15 ------ 7.841101396160445
15 ------ 5.255263829126264

C:\Users\rajkr\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

16 ------ inf
16 ------ 7.380644570758274
16 ------ 1.421011976182927
17 ------ 8.083354471350239
17 ------ 1.6241477619270313
18 ------ 7.257891375429919
18 ------ 15.596252041665208
18 ------ 1.8261329696765474
19 ------ 1.5080847785865648
20 ------ 2.172126715951356
21 ------ 2.623469861333444
22 ------ 2.296005407405737
23 ------ 7.36062257827916
23 ------ 2.1602388310452927
24 ------ 2.8686338012754247
25 ------ 6.458304472622984
25 ------ 2.847480877355158
26 ------ 4.753230129394101
27 ------ 16.22761360099179
27 ------ 6.424833892811067
27 ------ 8.887156094086976
27 ------ 2.38051089833245
28 ------ 8.609683496623786
28 ------ 13.067631026848238
28 ------ 3.500117421477055
29 ------ 1.909120174743784
30 ------ 17.007386818210737
30 ------ 10.730705629466753
30 ------ 2.3558875075565604
31 ------ 22.10495526579042
31 ------ 2.797253587418863
32 ------ 3.424180384313259
33 ------ 10.175437630379694
33 ------ 6.409440246481364
33 ------ 1.0011627214059167
34 ------ 3.069223764845478
35 ------ 2.8091270098505103
36 ------ 20.250688538227966
36 ------ 15.864583114854529
36 ------ 1.8332179956453987
37 ------ 1.56808804702165
38 ------ 1.9308798109877532
39 ------ 4.3316581441144475
40 ------ 12.394142002287238

In [29]:
len(columns_to_be_kept)

40

In [30]:
#check Anova for columncolumns_to_be_kept
from scipy.stats import f_oneway
columns_to_be_kept_numerical=[]
for i in columns_to_be_kept:
    a=list(df[i])
    b=list(df['Approved_Flag'])
    
    group_p1=[value for value , group in zip(a,b) if group =='P1']
    group_p2=[value for value , group in zip(a,b) if group =='P2']
    group_p3=[value for value , group in zip(a,b) if group =='P3']
    group_p4=[value for value , group in zip(a,b) if group =='P4']
    
    f_statistic,p_value=f_oneway(group_p1,group_p2,group_p3,group_p4)
    if p_value<=0.5:
        columns_to_be_kept_numerical.append(i)

In [31]:
columns_to_be_kept_numerical

['PROSPECTID',
 'pct_tl_open_L6M',
 'pct_tl_closed_L6M',
 'Tot_TL_closed_L12M',
 'pct_tl_closed_L12M',
 'Tot_Missed_Pmnt',
 'CC_TL',
 'Home_TL',
 'PL_TL',
 'Secured_TL',
 'Unsecured_TL',
 'Other_TL',
 'Age_Oldest_TL',
 'Age_Newest_TL',
 'time_since_recent_payment',
 'max_recent_level_of_deliq',
 'num_deliq_6_12mts',
 'num_times_60p_dpd',
 'num_std_12mts',
 'num_sub',
 'num_sub_6mts',
 'num_sub_12mts',
 'num_dbt',
 'num_dbt_12mts',
 'num_lss',
 'num_lss_12mts',
 'recent_level_of_deliq',
 'CC_enq_L12m',
 'PL_enq_L12m',
 'time_since_recent_enq',
 'enq_L3m',
 'NETMONTHLYINCOME',
 'Time_With_Curr_Empr',
 'CC_Flag',
 'PL_Flag',
 'pct_PL_enq_L6m_of_ever',
 'pct_CC_enq_L6m_of_ever',
 'HL_Flag',
 'GL_Flag']

In [32]:
len(columns_to_be_kept_numerical)

39

# Feature selection done adn now Label encoding for the categorical features

In [33]:
# listing all the final features
features = columns_to_be_kept_numerical + ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']
df = df[features + ['Approved_Flag']]

In [34]:
#so these are the unique values in these columns
df['MARITALSTATUS'].unique()
df['EDUCATION'].unique()
df['GENDER'].unique()
df['last_prod_enq2'].unique()
df['first_prod_enq2'].unique()

array(['PL', 'ConsumerLoan', 'others', 'AL', 'HL', 'CC'], dtype=object)

In [35]:
df['EDUCATION'].unique()

array(['12TH', 'GRADUATE', 'SSC', 'POST-GRADUATE', 'UNDER GRADUATE',
       'OTHERS', 'PROFESSIONAL'], dtype=object)

In [36]:
df['GENDER'].unique()

array(['M', 'F'], dtype=object)

In [37]:
df['last_prod_enq2'].unique()

array(['PL', 'ConsumerLoan', 'AL', 'CC', 'others', 'HL'], dtype=object)

In [38]:
df['first_prod_enq2'].unique()

array(['PL', 'ConsumerLoan', 'others', 'AL', 'HL', 'CC'], dtype=object)

In [39]:
# Now we are going to encoding

In [40]:
df.loc[df['EDUCATION']=='SSC',['EDUCATION']] =1
df.loc[df['EDUCATION']=='12TH',['EDUCATION']] =2
df.loc[df['EDUCATION']=='GRADUATE',['EDUCATION']] =3
df.loc[df['EDUCATION']=='UNDER GRADUATE',['EDUCATION']] =3
df.loc[df['EDUCATION']=='POST-GRADUATE',['EDUCATION']] =4
df.loc[df['EDUCATION']=='OTHERS',['EDUCATION']] =1
df.loc[df['EDUCATION']=='PROFESSIONAL',['EDUCATION']] =3

In [41]:
df['EDUCATION'].value_counts()

EDUCATION
3    18931
2    11703
1     9532
4     1898
Name: count, dtype: int64

In [42]:
df['EDUCATION']=df['EDUCATION'].astype('int')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 45 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   PROSPECTID                 42064 non-null  int64
 1   pct_tl_open_L6M            42064 non-null  float64
 2   pct_tl_closed_L6M          42064 non-null  float64
 3   Tot_TL_closed_L12M         42064 non-null  int64
 4   pct_tl_closed_L12M         42064 non-null  float64
 5   Tot_Missed_Pmnt            42064 non-null  int64
 6   CC_TL                      42064 non-null  int64
 7   Home_TL                    42064 non-null  int64
 8   PL_TL                      42064 non-null  int64
 9   Secured_TL                 42064 non-null  int64
 10  Unsecured_TL               42064 non-null  int64
 11  Other_TL                   42064 non-null  int64
 12  Age_Oldest_TL              42064 non-null  int64
 13  Age_Newest_TL              42064 non-null  int64
 14  time_since_recent_payment  42064 non-null  int64
 15  max_recent_level_of_deliq  42064 non-null  int64
 16  num_deliq_6_12mts          42064 non-null  int64
 17  num_times_60p_dpd          42064 non-null  int64
 18  num_std_12mts              42064 non-null  int64
 19  num_sub                    42064 non-null  int64
 20  num_sub_6mts               42064 non-null  int64
 21  num_sub_12mts              42064 non-null  int64
 22  num_dbt                    42064 non-null  int64
 23  num_dbt_12mts              42064 non-null  int64
 24  num_lss                    42064 non-null  int64
 25  num_lss_12mts              42064 non-null  int64
 26  recent_level_of_deliq      42064 non-null  int64
 27  CC_enq_L12m                42064 non-null  int64
 28  PL_enq_L12m                42064 non-null  int64
 29  time_since_recent_enq      42064 non-null  int64
 30  enq_L3m                    42064 non-null  int64
 31  NETMONTHLYINCOME           42064 non-null  int64
 32  Time_With_Curr_Empr        42064 non-null  int64
 33  CC_Flag                    42064 non-null  int64
 34  PL_Flag                    42064 non-null  int64
 35  pct_PL_enq_L6m_of_ever     42064 non-null  float64
 36  pct_CC_enq_L6m_of_ever     42064 non-null  float64
 37  HL_Flag                    42064 non-null  int64
 38  GL_Flag                    42064 non-null  int64
 39  MARITALSTATUS              42064 non-null  object
 40  EDUCATION                  42064 non-null  int32
 41  GENDER                     42064 non-null  object
 42  last_prod_enq2             42064 non-null  object
 43  first_prod_enq2            42064 non-null  object
 44  Approved_Flag              42064 non-null  object
dtypes: float64(5), int32(1), int64(34), object(5)
memory usage: 14.3+ MB

In [44]:
df_encoded=pd.get_dummies(df,columns=['MARITALSTATUS','GENDER','last_prod_enq2','first_prod_enq2'])

In [45]:
df_encoded.head()

,PROSPECTID,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,...,last_prod_enq2_ConsumerLoan,last_prod_enq2_HL,last_prod_enq2_PL,last_prod_enq2_others,first_prod_enq2_AL,first_prod_enq2_CC,first_prod_enq2_ConsumerLoan,first_prod_enq2_HL,first_prod_enq2_PL,first_prod_enq2_others
0,1,0.000,0.0,0,0.000,0,0,0,4,1,...,False,False,True,False,False,False,False,False,True,False
1,2,0.000,0.0,0,0.000,0,0,0,0,0,...,True,False,False,False,False,False,True,False,False,False
2,3,0.125,0.0,0,0.000,1,0,0,0,2,...,True,False,False,False,False,False,False,False,False,True
3,5,0.000,0.0,0,0.000,0,0,0,0,3,...,False,False,False,False,True,False,False,False,False,False
4,6,0.000,0.0,1,0.167,0,0,0,0,6,...,True,False,False,False,False,False,False,False,True,False

In [46]:
df_encoded.info()
k = df_encoded.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 57 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PROSPECTID                    42064 non-null  int64
 1   pct_tl_open_L6M               42064 non-null  float64
 2   pct_tl_closed_L6M             42064 non-null  float64
 3   Tot_TL_closed_L12M            42064 non-null  int64
 4   pct_tl_closed_L12M            42064 non-null  float64
 5   Tot_Missed_Pmnt               42064 non-null  int64
 6   CC_TL                         42064 non-null  int64
 7   Home_TL                       42064 non-null  int64
 8   PL_TL                         42064 non-null  int64
 9   Secured_TL                    42064 non-null  int64
 10  Unsecured_TL                  42064 non-null  int64
 11  Other_TL                      42064 non-null  int64
 12  Age_Oldest_TL                 42064 non-null  int64
 13  Age_Newest_TL                 42064 non-null  int64
 14  time_since_recent_payment     42064 non-null  int64
 15  max_recent_level_of_deliq     42064 non-null  int64
 16  num_deliq_6_12mts             42064 non-null  int64
 17  num_times_60p_dpd             42064 non-null  int64
 18  num_std_12mts                 42064 non-null  int64
 19  num_sub                       42064 non-null  int64
 20  num_sub_6mts                  42064 non-null  int64
 21  num_sub_12mts                 42064 non-null  int64
 22  num_dbt                       42064 non-null  int64
 23  num_dbt_12mts                 42064 non-null  int64
 24  num_lss                       42064 non-null  int64
 25  num_lss_12mts                 42064 non-null  int64
 26  recent_level_of_deliq         42064 non-null  int64
 27  CC_enq_L12m                   42064 non-null  int64
 28  PL_enq_L12m                   42064 non-null  int64
 29  time_since_recent_enq         42064 non-null  int64
 30  enq_L3m                       42064 non-null  int64
 31  NETMONTHLYINCOME              42064 non-null  int64
 32  Time_With_Curr_Empr           42064 non-null  int64
 33  CC_Flag                       42064 non-null  int64
 34  PL_Flag                       42064 non-null  int64
 35  pct_PL_enq_L6m_of_ever        42064 non-null  float64
 36  pct_CC_enq_L6m_of_ever        42064 non-null  float64
 37  HL_Flag                       42064 non-null  int64
 38  GL_Flag                       42064 non-null  int64
 39  EDUCATION                     42064 non-null  int32
 40  Approved_Flag                 42064 non-null  object
 41  MARITALSTATUS_Married         42064 non-null  bool
 42  MARITALSTATUS_Single          42064 non-null  bool
 43  GENDER_F                      42064 non-null  bool
 44  GENDER_M                      42064 non-null  bool
 45  last_prod_enq2_AL             42064 non-null  bool
 46  last_prod_enq2_CC             42064 non-null  bool
 47  last_prod_enq2_ConsumerLoan   42064 non-null  bool
 48  last_prod_enq2_HL             42064 non-null  bool
 49  last_prod_enq2_PL             42064 non-null  bool
 50  last_prod_enq2_others         42064 non-null  bool
 51  first_prod_enq2_AL            42064 non-null  bool
 52  first_prod_enq2_CC            42064 non-null  bool
 53  first_prod_enq2_ConsumerLoan  42064 non-null  bool
 54  first_prod_enq2_HL            42064 non-null  bool
 55  first_prod_enq2_PL            42064 non-null  bool
 56  first_prod_enq2_others        42064 non-null  bool
dtypes: bool(16), float64(5), int32(1), int64(34), object(1)
memory usage: 13.6+ MB

# Machnine Learning model fitting

In [47]:
#1 Random forest
y=df_encoded['Approved_Flag']
x=df_encoded.drop(['Approved_Flag'],axis=1)

In [48]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [49]:
#Random Forest 
rf_classifier=RandomForestClassifier(n_estimators=200,random_state=42)

In [50]:
rf_classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [51]:
y_pred=rf_classifier.predict(x_test)

In [52]:
accuracy=accuracy_score(y_test,y_pred)
print()
print(f'Accuracy :{accuracy}')
print()
precision,recall,f1_score,_=precision_recall_fscore_support(y_test,y_pred)

Accuracy :0.7666706287887792

In [53]:
for i ,v in enumerate(['p1','p2','p3','p4']):
    print(f"class {v}:")
    print(f"precision: {precision[i]}")
    print(f"recal : {recall[i]}")
    print(f"f1_score: {f1_score[i]}")
    print()

class p1:
precision: 0.8513189448441247
recal : 0.7001972386587771
f1_score: 0.7683982683982684

class p2:
precision: 0.7943405760485094
recal : 0.934786917740337
f1_score: 0.8588599526497905

class p3:
precision: 0.4504950495049505
recal : 0.2060377358490566
f1_score: 0.2827550491973071

class p4:
precision: 0.724903474903475
recal : 0.7298347910592808
f1_score: 0.7273607748184021

# XGBOOST

In [87]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-2.0.3-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\rajkr\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (1.25.2)
Requirement already satisfied: scipy in c:\users\rajkr\appdata\local\programs\python\python311\lib\site-packages (from xgboost) (1.11.3)
Downloading xgboost-2.0.3-py3-none-win_amd64.whl (99.8 MB)
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB 445.2 kB/s eta 0:03:44
   ---------------------------------------- 0.1/99.8 MB 660.6 kB/s eta 0:02:31
   ---------------------------------------- 0.3/99.8 MB 2.0 MB/s eta 0:00:51
   ---------------------------------------- 0.8/99.8 MB 4.5 MB/s eta 0:00:23
    --------------------------------------- 1.6/99.8 MB 7.5 MB/s eta 0:00:14
   - -------------------------------------- 2.8/99.8 MB 10.4 MB/s eta 0:00:10
   - -------------------------------------- 4.5/99.8 MB 14.2 MB/s eta 0:00:07
   -- ------------------------------------- 6.1/99.8 MB 17.0 MB/s eta 0:00:06
   --- ------------------------------------ 8.0/99.8 MB 19.6 MB/s eta 0:00:05
   --- ------------------------------------ 9.0/99.8 MB 19.2 MB/s eta 0:00:05
   --- ------------------------------------ 9.7/99.8 MB 19.5 MB/s eta 0:00:05
   ---- ----------------------------------- 10.5/99.8 MB 25.2 MB/s eta 0:00:04
   ----- ---------------------------------- 12.9/99.8 MB 31.2 MB/s eta 0:00:03
   ----- ---------------------------------- 14.4/99.8 MB 32.7 MB/s eta 0:00:03
   ------ --------------------------------- 15.9/99.8 MB 32.7 MB/s eta 0:00:03
   ------ --------------------------------- 16.9/99.8 MB 31.2 MB/s eta 0:00:03
   ------- -------------------------------- 18.5/99.8 MB 31.1 MB/s eta 0:00:03
   -------- ------------------------------- 20.2/99.8 MB 34.4 MB/s eta 0:00:03
   -------- ------------------------------- 21.6/99.8 MB 34.4 MB/s eta 0:00:03
   -------- ------------------------------- 21.9/99.8 MB 29.7 MB/s eta 0:00:03
   -------- ------------------------------- 22.3/99.8 MB 27.3 MB/s eta 0:00:03
   --------- ------------------------------ 22.5/99.8 MB 25.2 MB/s eta 0:00:04
   --------- ------------------------------ 22.5/99.8 MB 25.2 MB/s eta 0:00:04
   --------- ------------------------------ 23.6/99.8 MB 21.8 MB/s eta 0:00:04
   ---------- ----------------------------- 26.1/99.8 MB 22.6 MB/s eta 0:00:04
   ----------- ---------------------------- 27.9/99.8 MB 23.4 MB/s eta 0:00:04
   ----------- ---------------------------- 29.2/99.8 MB 23.4 MB/s eta 0:00:04
   ------------ --------------------------- 31.0/99.8 MB 23.4 MB/s eta 0:00:03
   ------------- -------------------------- 33.1/99.8 MB 43.7 MB/s eta 0:00:02
   ------------- -------------------------- 34.2/99.8 MB 40.9 MB/s eta 0:00:02
   -------------- ------------------------- 34.9/99.8 MB 36.3 MB/s eta 0:00:02
   -------------- ------------------------- 35.1/99.8 MB 32.7 MB/s eta 0:00:02
   -------------- ------------------------- 37.3/99.8 MB 32.7 MB/s eta 0:00:02
   --------------- ------------------------ 38.5/99.8 MB 32.7 MB/s eta 0:00:02
   --------------- ------------------------ 39.4/99.8 MB 32.7 MB/s eta 0:00:02
   ---------------- ----------------------- 40.4/99.8 MB 29.7 MB/s eta 0:00:02
   ---------------- ----------------------- 41.6/99.8 MB 28.4 MB/s eta 0:00:03
   ----------------- ---------------------- 42.6/99.8 MB 26.2 MB/s eta 0:00:03
   ----------------- ---------------------- 43.5/99.8 MB 24.2 MB/s eta 0:00:03
   ----------------- ---------------------- 44.4/99.8 MB 23.4 MB/s eta 0:00:03
   ------------------ --------------------- 45.4/99.8 MB 26.2 MB/s eta 0:00:03
   ------------------ --------------------- 46.5/99.8 MB 25.2 MB/s eta 0:00:03
   ------------------- -------------------- 47.5/99.8 MB 23.4 MB/s eta 0:00:03
   ------------------- -------------------- 48.1/99.8 MB 22.6 MB/s eta 0:00:03
   ------------------- -------------------- 48.7/99.8 MB 21.9 MB/s eta 0:00:03
   ------------------- -------------------- 49.3/99.8 MB 21.1 MB/s eta 0:00:03
   -------------------- ------------------- 50.1/99.8 MB 20.5 MB/s eta 0:00:03
   -------------------- ------------------- 50.9/99.8 MB 19.8 MB/s eta 0:00:03
   -------------------- ------------------- 51.5/99.8 MB 19.3 MB/s eta 0:00:03
   -------------------- ------------------- 52.0/99.8 MB 18.2 MB/s eta 0:00:03
   --------------------- ------------------ 52.7/99.8 MB 18.2 MB/s eta 0:00:03
   --------------------- ------------------ 53.0/99.8 MB 17.2 MB/s eta 0:00:03
   --------------------- ------------------ 53.7/99.8 MB 16.8 MB/s eta 0:00:03
   --------------------- ------------------ 54.3/99.8 MB 16.4 MB/s eta 0:00:03
   --------------------- ------------------ 54.5/99.8 MB 15.6 MB/s eta 0:00:03
   ---------------------- ----------------- 55.1/99.8 MB 15.6 MB/s eta 0:00:03
   ---------------------- ----------------- 55.7/99.8 MB 14.9 MB/s eta 0:00:03
   ---------------------- ----------------- 56.0/99.8 MB 13.9 MB/s eta 0:00:04
   ---------------------- ----------------- 56.6/99.8 MB 13.6 MB/s eta 0:00:04
   ---------------------- ----------------- 57.2/99.8 MB 13.4 MB/s eta 0:00:04
   ----------------------- ---------------- 57.4/99.8 MB 13.1 MB/s eta 0:00:04
   ----------------------- ---------------- 57.7/99.8 MB 12.4 MB/s eta 0:00:04
   ----------------------- ---------------- 58.0/99.8 MB 12.4 MB/s eta 0:00:04
   ----------------------- ---------------- 58.2/99.8 MB 11.7 MB/s eta 0:00:04
   ----------------------- ---------------- 58.2/99.8 MB 11.5 MB/s eta 0:00:04
   ----------------------- ---------------- 58.5/99.8 MB 10.9 MB/s eta 0:00:04
   ----------------------- ---------------- 59.0/99.8 MB 10.4 MB/s eta 0:00:04
   ----------------------- ---------------- 59.4/99.8 MB 10.4 MB/s eta 0:00:04
   ----------------------- ---------------- 59.8/99.8 MB 10.2 MB/s eta 0:00:04
   ------------------------ --------------- 59.9/99.8 MB 9.8 MB/s eta 0:00:05
   ------------------------ --------------- 60.1/99.8 MB 9.9 MB/s eta 0:00:04
   ------------------------ --------------- 60.5/99.8 MB 9.4 MB/s eta 0:00:05
   ------------------------ --------------- 60.7/99.8 MB 9.2 MB/s eta 0:00:05
   ------------------------ --------------- 61.0/99.8 MB 8.8 MB/s eta 0:00:05
   ------------------------ --------------- 61.2/99.8 MB 8.6 MB/s eta 0:00:05
   ------------------------ --------------- 61.6/99.8 MB 8.6 MB/s eta 0:00:05
   ------------------------ --------------- 62.0/99.8 MB 8.4 MB/s eta 0:00:05
   ------------------------ --------------- 62.2/99.8 MB 8.3 MB/s eta 0:00:05
   ------------------------- -------------- 63.1/99.8 MB 8.3 MB/s eta 0:00:05
   ------------------------- -------------- 63.5/99.8 MB 8.3 MB/s eta 0:00:05
   ------------------------- -------------- 63.9/99.8 MB 8.2 MB/s eta 0:00:05
   ------------------------- -------------- 64.1/99.8 MB 8.1 MB/s eta 0:00:05
   ------------------------- -------------- 64.2/99.8 MB 7.9 MB/s eta 0:00:05
   -------------------------- ------------- 65.1/99.8 MB 8.0 MB/s eta 0:00:05
   -------------------------- ------------- 65.3/99.8 MB 7.9 MB/s eta 0:00:05
   -------------------------- ------------- 65.6/99.8 MB 7.9 MB/s eta 0:00:05
   -------------------------- ------------- 65.9/99.8 MB 7.8 MB/s eta 0:00:05
   -------------------------- ------------- 66.2/99.8 MB 7.6 MB/s eta 0:00:05
   -------------------------- ------------- 67.1/99.8 MB 7.7 MB/s eta 0:00:05
   --------------------------- ------------ 67.6/99.8 MB 7.8 MB/s eta 0:00:05
   --------------------------- ------------ 68.3/99.8 MB 8.3 MB/s eta 0:00:04
   --------------------------- ------------ 69.1/99.8 MB 9.2 MB/s eta 0:00:04
   ---------------------------- ----------- 70.2/99.8 MB 9.9 MB/s eta 0:00:03
   ---------------------------- ----------- 71.0/99.8 MB 11.3 MB/s eta 0:00:03
   ---------------------------- ----------- 71.4/99.8 MB 11.5 MB/s eta 0:00:03
   ---------------------------- ----------- 72.1/99.8 MB 12.1 MB/s eta 0:00:03
   ----------------------------- ---------- 72.9/99.8 MB 12.8 MB/s eta 0:00:03
   ----------------------------- ---------- 73.3/99.8 MB 12.4 MB/s eta 0:00:03
   ----------------------------- ---------- 73.7/99.8 MB 12.1 MB/s eta 0:00:03
   ----------------------------- ---------- 74.2/99.8 MB 12.4 MB/s eta 0:00:03
   ----------------------------- ---------- 74.7/99.8 MB 13.1 MB/s eta 0:00:02
   ----------------------------- ---------- 74.7/99.8 MB 13.1 MB/s eta 0:00:02
   ------------------------------ --------- 74.9/99.8 MB 11.9 MB/s eta 0:00:03
   ------------------------------ --------- 75.7/99.8 MB 12.4 MB/s eta 0:00:02
   ------------------------------ --------- 75.8/99.8 MB 12.4 MB/s eta 0:00:02
   ------------------------------ --------- 75.9/99.8 MB 11.9 MB/s eta 0:00:03
   ------------------------------ --------- 76.2/99.8 MB 11.5 MB/s eta 0:00:03
   ------------------------------ --------- 76.4/99.8 MB 11.5 MB/s eta 0:00:03
   ------------------------------ --------- 76.7/99.8 MB 10.9 MB/s eta 0:00:03
   ------------------------------- -------- 77.3/99.8 MB 10.9 MB/s eta 0:00:03
   ------------------------------- -------- 78.2/99.8 MB 10.9 MB/s eta 0:00:02
   ------------------------------- -------- 78.9/99.8 MB 11.1 MB/s eta 0:00:02
   -------------------------------- ------- 79.9/99.8 MB 10.9 MB/s eta 0:00:02
   -------------------------------- ------- 80.8/99.8 MB 11.1 MB/s eta 0:00:02
   -------------------------------- ------- 81.6/99.8 MB 11.1 MB/s eta 0:00:02
   -------------------------------- ------- 82.3/99.8 MB 11.3 MB/s eta 0:00:02
   --------------------------------- ------ 83.0/99.8 MB 11.3 MB/s eta 0:00:02
   --------------------------------- ------ 83.6/99.8 MB 11.7 MB/s eta 0:00:02
   --------------------------------- ------ 84.1/99.8 MB 12.1 MB/s eta 0:00:02
   ---------------------------------- ----- 84.9/99.8 MB 13.1 MB/s eta 0:00:02
   ---------------------------------- ----- 85.8/99.8 MB 13.6 MB/s eta 0:00:02
   ---------------------------------- ----- 86.8/99.8 MB 18.2 MB/s eta 0:00:01
   ----------------------------------- ---- 87.6/99.8 MB 19.3 MB/s eta 0:00:01
   ----------------------------------- ---- 88.0/99.8 MB 18.2 MB/s eta 0:00:01
   ----------------------------------- ---- 88.2/99.8 MB 17.7 MB/s eta 0:00:01
   ----------------------------------- ---- 88.7/99.8 MB 17.3 MB/s eta 0:00:01
   ----------------------------------- ---- 89.4/99.8 MB 16.4 MB/s eta 0:00:01
   ------------------------------------ --- 90.0/99.8 MB 16.4 MB/s eta 0:00:01
   ------------------------------------ --- 90.6/99.8 MB 16.0 MB/s eta 0:00:01
   ------------------------------------ --- 91.1/99.8 MB 15.6 MB/s eta 0:00:01
   ------------------------------------ --- 91.5/99.8 MB 14.9 MB/s eta 0:00:01
   ------------------------------------ --- 92.1/99.8 MB 14.9 MB/s eta 0:00:01
   ------------------------------------- -- 92.9/99.8 MB 14.5 MB/s eta 0:00:01
   ------------------------------------- -- 93.7/99.8 MB 14.9 MB/s eta 0:00:01
   ------------------------------------- -- 94.7/99.8 MB 15.6 MB/s eta 0:00:01
   -------------------------------------- - 95.4/99.8 MB 15.2 MB/s eta 0:00:01
   -------------------------------------- - 96.5/99.8 MB 15.2 MB/s eta 0:00:01
   ---------------------------------------  97.5/99.8 MB 15.6 MB/s eta 0:00:01
   ---------------------------------------  98.5/99.8 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------  99.4/99.8 MB 18.2 MB/s eta 0:00:01
   ---------------------------------------  99.7/99.8 MB 18.2 MB/s eta 0:00:01
   ---------------------------------------  99.7/99.8 MB 18.2 MB/s eta 0:00:01
   ---------------------------------------  99.7/99.8 MB 18.2 MB/s eta 0:00:01
   ---------------------------------------  99.7/99.8 MB 18.2 MB/s eta 0:00:01
   ---------------------------------------  99.7/99.8 MB 18.2 MB/s eta 0:00:01
   ---------------------------------------  99.7/99.8 MB 18.2 MB/s eta 0:00:01
   ---------------------------------------- 99.8/99.8 MB 11.9 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-2.0.3
Note: you may need to restart the kernel to use updated packages.

In [54]:
import xgboost as xgb
#from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import LabelEncoder

In [55]:
xgb_classifier=xgb.XGBClassifier(objective='multi:softmax',num_class=4)

In [56]:
y=df_encoded['Approved_Flag']
x=df_encoded.drop(['Approved_Flag'],axis=1)

In [57]:
label_encoder=LabelEncoder()
y_encoded=label_encoder.fit_transform(y)

In [58]:
x_train,x_test,y_train,y_test=train_test_split(x,y_encoded,test_size=0.2,random_state=42)

In [59]:
xgb_classifier.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=4,
              num_parallel_tree=None, ...)

In [60]:
y_pred=xgb_classifier.predict(x_test)

In [61]:
y_pred

array([1, 3, 1, ..., 1, 1, 3])

In [62]:
accuracy=accuracy_score(y_test,y_pred)
print()
print(f'Accuracy :{accuracy:.2f}')
print()
precision,recall,f1_score,_=precision_recall_fscore_support(y_test,y_pred)

Accuracy :0.78

In [63]:
for i ,v in enumerate(['p1','p2','p3','p4']):
    print(f"class {v}:")
    print(f"precision: {precision[i]}")
    print(f"recal : {recall[i]}")
    print(f"f1_score: {f1_score[i]}")
    print()

class p1:
precision: 0.823093220338983
recal : 0.7662721893491125
f1_score: 0.7936670071501533

class p2:
precision: 0.8236559139784946
recal : 0.9110009910802775
f1_score: 0.8651294117647058

class p3:
precision: 0.4638196915776987
recal : 0.29509433962264153
f1_score: 0.36070110701107017

class p4:
precision: 0.7237093690248566
recal : 0.7356656948493683
f1_score: 0.7296385542168674

In [64]:
# 3. Decision Tree
from sklearn.tree import DecisionTreeClassifier

In [65]:
y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

In [66]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [67]:

dt_model = DecisionTreeClassifier(max_depth=20, min_samples_split=10)
dt_model.fit(x_train, y_train)
y_pred = dt_model.predict(x_test)

In [68]:
accuracy = accuracy_score(y_test, y_pred)
print ()
print(f"Accuracy: {accuracy:.2f}")
print ()

Accuracy: 0.71

In [69]:
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Class p1:
Precision: 0.7323383084577114
Recall: 0.7258382642998028
F1 Score: 0.7290737989103516

Class p2:
Precision: 0.8097362296353763
Recall: 0.8275520317145689
F1 Score: 0.818547201254779

Class p3:
Precision: 0.3442622950819672
Recall: 0.3169811320754717
F1 Score: 0.33005893909626716

Class p4:
Precision: 0.6375968992248062
Recall: 0.6394557823129252
F1 Score: 0.6385249878699661

# Hypeparameter tunning in Xgboost

In [70]:
param_grid={
    'colsample_bytree':[0.1,0.3,0.5,0.7,0.9],
    'learning_rate':[0.001,0.01,0.1,1],
    'max_depth':[3,5,8,10],
    'alpha':[1,10,100],
    'n_estimators':[10,50,100]
}

In [71]:
index=0

In [72]:
answers_grid={
    'combination':[],
    'train_Accuracy':[],
    'test_Accuracy':[],
    'colsample_bytree':[],
    'learning_rate':[],
    'max_depth':[],
    'alpha':[],
    'n_estimators':[]
}

In [ ]:
#loop through each combination of hyperparameter
for colsample_bytree in param_grid['colsample_bytree']:
    for learning_rate in param_grid['learning_rate']:
        for max_depth in param_grid['max_depth']:
            for alpha in param_grid['alpha']:
                for n_estimators in param_grid['n_estimators']:
                    index=index+1
                    # Define and train the Xgboost model
                    model=xgb.XGBClassifier(objective='multi:softmax',
                                                num_class=4,
                                                colsample_bytree=colsample_bytree,
                                                learning_rate=learning_rate,
                                                max_depth=max_depth,
                                                alpha=alpha,
                                                n_estimators=n_estimators)
                    y=df_encoded['Approved_Flag']
                    x=df_encoded.drop(['Approved_Flag'],axis=1)
                    label_encoder=LabelEncoder()
                    y_encoded=label_encoder.fit_transform(y)

                    x_train,x_test,y_train,y_test=train_test_split(x,y_encoded,test_size=0.2,random_state=42)
                    model.fit(x_train,y_train)

                    #predict on training and testing sets
                    y_pred_train=model.predict(x_train)
                    y_pred_test=model.predict(x_test)

                    #calculate train and test results
                    train_accuracy=accuracy_score(y_train,y_pred_train)
                    test_accuracy=accuracy_score(y_test,y_pred_test)

                    #Include into the lists
                    answers_grid['combination'].append(index)
                    answers_grid['train_Accuracy'].append(train_accuracy)
                    answers_grid['test_Accuracy'].append(test_accuracy)
                    answers_grid['colsample_bytree'].append(colsample_bytree)
                    answers_grid['learning_rate'].append(learning_rate)
                    answers_grid['max_depth'].append(max_depth)
                    answers_grid['alpha'].append(alpha)
                    answers_grid['n_estimators'].append(n_estimators)
                    # Print results for this combination
                    print(f"Combination {index}")
                    print(f"colsample_bytree: {colsample_bytree}, learning_rate: {learning_rate}, max_depth: {max_depth}, alpha: {alpha}, n_estimators: {n_estimators}")
                    print(f"Train Accuracy: {train_accuracy:.2f}")
                    print(f"Test Accuracy : {test_accuracy :.2f}")
                    print("-" * 30)

In [73]:
# validating our model on unseen data
unseen=pd.read_excel("Unseen_Dataset.xlsx")

In [74]:
unseen.head()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2
0,0.000,0.0,0,0.000,0,0,0,4,1,4,...,1,0.000,0.0,1,0,Married,12TH,M,PL,PL
1,0.000,0.0,0,0.000,0,0,0,0,0,1,...,0,0.000,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan
2,0.125,0.0,0,0.000,1,0,0,0,2,6,...,0,0.000,0.0,1,0,Married,SSC,M,ConsumerLoan,others
3,0.000,0.0,0,0.000,0,0,0,0,3,0,...,0,0.000,0.0,0,0,Married,POST-GRADUATE,M,AL,AL
4,0.000,0.0,1,0.167,0,0,0,0,6,0,...,0,0.429,0.0,1,0,Married,12TH,M,ConsumerLoan,PL

In [78]:
cols_in_df=list(unseen.columns)
cols_in_df.pop()

'first_prod_enq2'

In [79]:
df_unseen=unseen[cols_in_df]